using System;
using OpenQA.Selenium;
using QAAutomation.Core.Configuration;
using QAAutomation.Core.Utilities;

namespace QAAutomation.UI.Pages
{
    /// <summary>
    /// The public enquiry page of the site under test.
    ///
    /// ===================================================================================
    /// READ THIS BEFORE CHANGING ANYTHING IN THIS FILE.
    ///
    /// THIS IS A PRODUCTION WEBSITE, AND THIS PAGE OBJECT IS READ-ONLY BY DESIGN.
    ///
    /// The site belongs to Landmark Systems and is their live, customer-facing site. The form
    /// on this page is their real sales enquiry form. A successful submit does not land in a
    /// test database - it creates a REAL SALES ENQUIRY that a real person at Landmark has to
    /// read and answer. Automating that would be sending someone else's business a stream of
    /// junk leads.
    ///
    /// There is also nothing to gain from it. The live form carries the HTML "novalidate"
    /// attribute, which switches off browser validation completely, so there is NO client-side
    /// validation to assert on. The only validation that exists runs on the server, behind an
    /// AJAX POST - in other words, behind exactly the submit we are not allowed to make.
    ///
    /// SO THIS CLASS HAS NO SUBMIT METHOD, AND NONE MAY BE ADDED. No Submit(), no
    /// SubmitEnquiry(), no click on a submit control, no form POST. The absence is the control:
    /// if the method does not exist, nobody can "just finish" the scenario later by calling it,
    /// and a reviewer can see the rule has been kept by reading this file.
    ///
    /// What the suite proves instead, without writing anything: the form declares which of its
    /// fields are mandatory (aria-required), and it holds the details a visitor types. Both are
    /// read-only checks of the same contract a submit would have exercised.
    /// ===================================================================================
    ///
    /// LOCATOR NOTE - A DELIBERATE, DOCUMENTED EXCEPTION.
    /// .kiro/steering/ui-automation-selenium.md section 1 makes data-testid the default locator
    /// strategy. A third-party WordPress site has none and we cannot add any, so this file uses
    /// the most stable selectors the site actually offers: the Gravity Forms field ids below.
    /// On KEYinfinity data-testid becomes the primary strategy again. Any XPath added here must
    /// carry its own inline justification; there is none at the moment.
    ///
    /// Methods are synchronous because Selenium's C# API is synchronous. Nothing here asserts.
    /// </summary>
    public class ContactUsPage
    {
        // Gravity Forms gives every input a predictable id of the shape
        // input_<formId>_<fieldId>. The enquiry form on this page is form 2, so every id below
        // starts input_2_. These ids are generated by the plugin from the form definition, not
        // hand-written by a developer, which is what makes them the most stable thing on the
        // page - but they are still someone else's content, so they are collected here in one
        // block. If Landmark rebuilds the form, this block is the only thing that changes.
        private const string FirstNameFieldId = "input_2_5";
        private const string SurnameFieldId = "input_2_19";
        private const string PostcodeFieldId = "input_2_6";
        private const string EmailAddressFieldId = "input_2_7";
        private const string TelephoneFieldId = "input_2_8";
        private const string CompanyNameFieldId = "input_2_4";
        private const string MobileFieldId = "input_2_9";
        private const string YourEnquiryFieldId = "input_2_10";

        // The names scenarios use. They are the labels a visitor reads on the page, so a
        // feature file can say "the Email address field" and mean something to a human.
        private const string FirstNameFieldName = "First Name";
        private const string SurnameFieldName = "Surname";
        private const string PostcodeFieldName = "Postcode";
        private const string EmailAddressFieldName = "Email address";
        private const string TelephoneFieldName = "Telephone";
        private const string CompanyNameFieldName = "Company Name";
        private const string MobileFieldName = "Mobile";
        private const string YourEnquiryFieldName = "Your Enquiry";

        // The attribute the form uses to declare that a field must be filled in, and the value
        // it carries when it is. Read, never written.
        private const string MandatoryAttributeName = "aria-required";
        private const string MandatoryAttributeValue = "true";

        // The DOM property that holds what is currently typed into an input. The "value"
        // attribute only shows the starting value from the HTML, so reading the property is the
        // way to see what the visitor actually typed.
        private const string ValuePropertyName = "value";

        // The page's own anchor for the form section, the one its "COMPLETE FORM" button links
        // to. Open() navigates straight to it, and that is load-bearing - see the long note on
        // Open() below.
        private const string FormSectionAnchor = "#form";

        private static readonly FormField[] Fields = new FormField[]
        {
            new FormField(FirstNameFieldName, By.Id(FirstNameFieldId)),
            new FormField(SurnameFieldName, By.Id(SurnameFieldId)),
            new FormField(PostcodeFieldName, By.Id(PostcodeFieldId)),
            new FormField(EmailAddressFieldName, By.Id(EmailAddressFieldId)),
            new FormField(TelephoneFieldName, By.Id(TelephoneFieldId)),
            new FormField(CompanyNameFieldName, By.Id(CompanyNameFieldId)),
            new FormField(MobileFieldName, By.Id(MobileFieldId)),
            new FormField(YourEnquiryFieldName, By.Id(YourEnquiryFieldId))
        };

        private readonly IWebDriver driver;
        private readonly SiteOptions siteOptions;
        private readonly ElementWaits waits;

        public ContactUsPage(IWebDriver driver, SiteOptions siteOptions, ElementWaits waits)
        {
            this.driver = driver;
            this.siteOptions = siteOptions;
            this.waits = waits;
        }

        /// <summary>
        /// Opens the enquiry page and waits until the first field is genuinely on screen.
        ///
        /// WHY THE URL ENDS IN #form, AND WHY REMOVING IT BREAKS EVERY SCENARIO IN THIS FILE.
        ///
        /// The site reveals the form with a scroll animation. Until the form scrolls into view
        /// its container is left at zero opacity, and Selenium treats a zero-opacity element as
        /// not displayed - correctly, because a visitor cannot see it either. So a wait for the
        /// first field on the plain /contact-us/ address times out after the full twenty
        /// seconds, even though the fields are sitting right there in the page source. That is a
        /// genuinely confusing failure, which is why it is written down here.
        ///
        /// Navigating to the page's own #form anchor - the same place its "COMPLETE FORM"
        /// button points - lands the browser on the form section, the reveal runs, and the
        /// fields become visible. It also happens to be the quickest route, which is what a
        /// visitor clicking that button is after.
        ///
        /// There is a second reason not to click the button instead. Ten seconds after the page
        /// loads, a newsletter sign-up panel covers the whole window, and a click on anything
        /// underneath it would be refused. Jumping straight to the anchor needs no click at
        /// all, so this page object never races that ten-second timer. Reading an attribute and
        /// typing into a field both keep working while the panel is up, so there is nothing to
        /// dismiss and nothing to tidy up.
        /// </summary>
        public void Open()
        {
            string contactPageUrl = this.siteOptions.BaseUrl + this.siteOptions.ContactPagePath + FormSectionAnchor;
            this.driver.Navigate().GoToUrl(contactPageUrl);

            By firstFieldLocator = LocatorFor(FirstNameFieldName);
            this.waits.WaitUntilVisible(firstFieldLocator);
        }

        /// <summary>
        /// True when the form declares the field as one the visitor has to fill in.
        ///
        /// This reads the form's own declaration (aria-required), which is also what a screen
        /// reader announces. It is a read of the published contract, not a guess, and it needs
        /// no submit.
        /// </summary>
        public bool IsFieldMandatory(string fieldName)
        {
            By locator = LocatorFor(fieldName);
            IWebElement field = this.waits.WaitUntilVisible(locator);

            string declaredValue = field.GetDomAttribute(MandatoryAttributeName);
            if (declaredValue == null)
            {
                // An optional field simply does not carry the attribute at all.
                return false;
            }

            return string.Equals(declaredValue, MandatoryAttributeValue, StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>Types a value into a field, replacing anything already in it.</summary>
        public void TypeInto(string fieldName, string value)
        {
            By locator = LocatorFor(fieldName);
            IWebElement field = this.waits.WaitUntilClickable(locator);

            field.Clear();
            field.SendKeys(value);
        }

        /// <summary>What the field is currently holding.</summary>
        public string ReadValueOf(string fieldName)
        {
            By locator = LocatorFor(fieldName);
            IWebElement field = this.waits.WaitUntilVisible(locator);

            return field.GetDomProperty(ValuePropertyName);
        }

        private static By LocatorFor(string fieldName)
        {
            foreach (FormField field in Fields)
            {
                if (string.Equals(field.FieldName, fieldName, StringComparison.OrdinalIgnoreCase))
                {
                    return field.Locator;
                }
            }

            throw new ArgumentException(
                "The enquiry form has no field called '" + fieldName + "'. The field names this page "
                + "knows about are: First Name, Surname, Postcode, Email address, Telephone, "
                + "Company Name, Mobile, Your Enquiry. Check the spelling in the feature file.",
                nameof(fieldName));
        }

        /// <summary>
        /// One row of the field table above: the name a scenario uses, and how to find it.
        /// A tiny holder rather than a tuple, so the two halves have readable names.
        /// </summary>
        private sealed class FormField
        {
            public FormField(string fieldName, By locator)
            {
                this.FieldName = fieldName;
                this.Locator = locator;
            }

            public string FieldName { get; private set; }

            public By Locator { get; private set; }
        }
    }
}
